### ISSUE TITLE
Fails to process decimals

### ISSUE THREAD

**Issue by vicp-iq** [mikeclayton/MofParser#5]
The following fails to process:

```
instance of MSFT_SomeResource as $Alias00000071
{
    Number = 3.91;
};
```

**Comment by mikeclayton** [comment]
The number lexer is pretty limited right now. It only really handles integers - see src/Kingsland.MofParser/Lexing/Lexer.cs line 139-142

                    else if ((peek.Value == '+') || (peek.Value == '-') ||
                             (StringValidator.IsDecimalDigit(peek.Value)))
                    {
                        return Lexer.ReadIntegerLiteralToken(stream);
                    }

I'm happy to take a look at a PR if you've got one that adds support for reals / decimals?

**Comment by vicp-iq** [comment]
If I find the time to fix it, then I'll definitely create a PR for it.  I have no time estimates right now.

**Comment by mikeclayton** [comment]
I've done a major rewrite of the IntegerValueToken and RealValueToken lexer code to implement all the "integerValue = binaryValue / octalValue / hexValue / integerValue" subtypes and most of the realValue spec (everything except exponent notation) as well as compatibility with MOF spec 3.0.1.

See PR #14 and commit https://github.com/mikeclayton/MofParser/pull/14/commits/673e0ac7184034671a24c0cfa58726fab875f340 for the changes to support integerValue and realValue.

It's a bit of a monstrous state machine which could probably do with some refactoring and optimisation, but all the new "ShouldRead[Binary|Octal|Hex|Decimal|Real]Value" tests that I've added to src/Kingsland.MofParser.UnitTests/Lexer/LexerTests.cs pass at the moment so I think it'll do as a starting point.

**Comment by vicp-iq** [comment]
Thanks! We con close this now.
